language: node_js
matrix:
  include:
    - node_js: "12"
dist: trusty
cache:
  directories:
    - node_modules
install:
  - bash pika install
script:
  - bash pika build
after_success:
  - bash pika test
